name: glfw
description: GLFW3 Dart bindings.
version: 1.0.0

environment:
  sdk: '>=2.15.0-82.0.dev <3.0.0'

dependencies: 
  dylib: ^0.3.2+1
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^4.1.1
  lints: ^1.0.0
  tests: ^1.0.0+1

ffigen:
  name: GLFW
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - 'ffi/glfw3.h'
      - 'ffi/glfw3native.h'